import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageProvider from "@/components/LanguageProvider";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/components/ThemeProvider";
import CartProvider from "@/components/CartProvider";
import FavoritesProvider from "@/components/FavoritesProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "اركان",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ar"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          <ThemeProvider>
            <CartProvider>
              <FavoritesProvider>
                <Navbar />
                {children}
              </FavoritesProvider>
            </CartProvider>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>

  );
}
